management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8084
spring:
  application:
    name: nacos-customer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
